description: "default config"
runner: r001
SINGLE_FOLD: true
split:
    split_type: kf
    split_num: 5
    shuffle: true
    random_state: 71
loader:
    trn_sampler_type: random
    trn_batch_size: 32
    tst_sampler_type: sequential
    tst_batch_size: 32
    dataset_type: open_vaccine_dataset
    # dataset:
    #     tokenizer_type: open_vaccine_dataset
model:
    model_type: guchio_gru_1
    # seq_len: 107
    # pred_len: 68
    num_layers: 3
    dropout: 0.5
    num_embeddings: 14
    embed_dim: 64
    out_dim: 3
fobj:
    fobj_type: mcrmse
optimizer:
    optim_type: adam
    lr: 0.0003
scheduler:
    scheduler_type: cosine
    every_step_unit: 0.2
    cosine_eta_min: 0.000001
    multistep_milestones:
        - 1
        - 3
    multistep_gamma: 0.2
train:
    max_epoch: 50
    warmup_epoch: 0
    warmup_batch: 0
    ema_mu: 0.9
    ema_level: batch
    ema_n: 0  # < 1 means no ema
    accum_mod: 1
    loss_weight_type: nothing
    pseudo: false
predict:
