description: "e023 adam"
runner: r001
SINGLE_FOLD: false
train:
loader:
    trn_batch_size: 64
    tst_batch_size: 64
model:
    model_type: guchio_gru_1
    num_layers: 3
    num_lstm_layers: 0
    bilstm: true
    embed_dim: 96
    embed_dropout: 0.2
optimizer:
    optim_type: adam
    lr: 0.001
scheduler:
    scheduler_type: cosine
    cosine_eta_min: 0.0003
train:
    max_epoch: 100
    sn_filter: false
    signal_to_noise_thresh: 1
features:
    - bpp_max_stand
    - bpp_sum_stand
    - bpp_non_zero_ratio_stand
    - structure_dist_stand
    - structure_depth_stand
